- hosts: all
  become: yes
  tasks:
    - name: create the 'jenkins' user
      user: name=jenkins append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'jenkins' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the jenkins user
      authorized_key: user=jenkins key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
